package com.scoutin.entities;

// Generated Apr 4, 2013 10:13:24 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable, AuthenticateType {

	private Integer accountId;
	private String password;
	private String email;
	private String username;
	private String facebookId;
	private String twitterId;
	private Date createdTime;
	private Date updatedTime;
	private Set albums = new HashSet(0);
	private Stat stat;
	private Profile profile;
	private Set followersForFollowingId = new HashSet(0);
	private Set cards = new HashSet(0);
	private Set cards_1 = new HashSet(0);
	private Set comments = new HashSet(0);
	private Set followersForFollowedId = new HashSet(0);

	public Account() {
	}

	public Account(String password) {
		this.password = password;
	}

	public Account(String password, String email, String username,
			String facebookId, String twitterId, Date createdTime,
			Date updatedTime, Set albums, Stat stat, Profile profile,
			Set followersForFollowingId, Set cards, Set cards_1, Set comments,
			Set followersForFollowedId) {
		this.password = password;
		this.email = email;
		this.username = username;
		this.facebookId = facebookId;
		this.twitterId = twitterId;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.albums = albums;
		this.stat = stat;
		this.profile = profile;
		this.followersForFollowingId = followersForFollowingId;
		this.cards = cards;
		this.cards_1 = cards_1;
		this.comments = comments;
		this.followersForFollowedId = followersForFollowedId;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFacebookId() {
		return this.facebookId;
	}

	public void setFacebookId(String facebookId) {
		this.facebookId = facebookId;
	}

	public String getTwitterId() {
		return this.twitterId;
	}

	public void setTwitterId(String twitterId) {
		this.twitterId = twitterId;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Set getAlbums() {
		return this.albums;
	}

	public void setAlbums(Set albums) {
		this.albums = albums;
	}

	public Stat getStat() {
		return this.stat;
	}

	public void setStat(Stat stat) {
		this.stat = stat;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public Set getFollowersForFollowingId() {
		return this.followersForFollowingId;
	}

	public void setFollowersForFollowingId(Set followersForFollowingId) {
		this.followersForFollowingId = followersForFollowingId;
	}

	public Set getCards() {
		return this.cards;
	}

	public void setCards(Set cards) {
		this.cards = cards;
	}

	public Set getCards_1() {
		return this.cards_1;
	}

	public void setCards_1(Set cards_1) {
		this.cards_1 = cards_1;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set getFollowersForFollowedId() {
		return this.followersForFollowedId;
	}

	public void setFollowersForFollowedId(Set followersForFollowedId) {
		this.followersForFollowedId = followersForFollowedId;
	}

}
