package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private Integer accountId;
	private String password;
	private String email;
	private String username;
	private String facebookId;
	private String twitterId;
	private Date createdTime;
	private Date updatedTime;

	public Account() {
	}

	public Account(String password) {
		this.password = password;
	}

	public Account(String password, String email, String username,
			String facebookId, String twitterId, Date createdTime,
			Date updatedTime) {
		this.password = password;
		this.email = email;
		this.username = username;
		this.facebookId = facebookId;
		this.twitterId = twitterId;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFacebookId() {
		return this.facebookId;
	}

	public void setFacebookId(String facebookId) {
		this.facebookId = facebookId;
	}

	public String getTwitterId() {
		return this.twitterId;
	}

	public void setTwitterId(String twitterId) {
		this.twitterId = twitterId;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
