package com.scoutin.entities;

// Generated Apr 16, 2013 2:22:33 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Accountstat generated by hbm2java
 */
public class Accountstat implements java.io.Serializable {

	private Integer accountId;
	private Account account;
	private Integer followingCount;
	private Integer followersCount;
	private Date lastRecmdView;
	private Integer unviewRecmdCount;

	public Accountstat() {
	}

	public Accountstat(Account account) {
		this.account = account;
	}

	public Accountstat(Account account, Integer followingCount,
			Integer followersCount, Date lastRecmdView, Integer unviewRecmdCount) {
		this.account = account;
		this.followingCount = followingCount;
		this.followersCount = followersCount;
		this.lastRecmdView = lastRecmdView;
		this.unviewRecmdCount = unviewRecmdCount;
	}

	public Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(Integer accountId) {
		this.accountId = accountId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Integer getFollowingCount() {
		return this.followingCount;
	}

	public void setFollowingCount(Integer followingCount) {
		this.followingCount = followingCount;
	}

	public Integer getFollowersCount() {
		return this.followersCount;
	}

	public void setFollowersCount(Integer followersCount) {
		this.followersCount = followersCount;
	}

	public Date getLastRecmdView() {
		return this.lastRecmdView;
	}

	public void setLastRecmdView(Date lastRecmdView) {
		this.lastRecmdView = lastRecmdView;
	}

	public Integer getUnviewRecmdCount() {
		return this.unviewRecmdCount;
	}

	public void setUnviewRecmdCount(Integer unviewRecmdCount) {
		this.unviewRecmdCount = unviewRecmdCount;
	}

}
