package com.scoutin.entities;

// Generated Apr 12, 2013 7:16:42 AM by Hibernate Tools 4.0.0

/**
 * Albumcard generated by hbm2java
 */
public class Albumcard implements java.io.Serializable {

	private AlbumcardId id;

	public Albumcard() {
	}

	public Albumcard(AlbumcardId id) {
		this.id = id;
	}

	public AlbumcardId getId() {
		return this.id;
	}

	public void setId(AlbumcardId id) {
		this.id = id;
	}

}
