package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Album generated by hbm2java
 */
public class Album implements java.io.Serializable {

	private Long albumId;
	private int accountId;
	private String name;
	private String coverPath;
	private Date createdTime;
	private Date updatedTime;
	private Integer followCount;

	public Album() {
	}

	public Album(int accountId) {
		this.accountId = accountId;
	}

	public Album(int accountId, String name, String coverPath,
			Date createdTime, Date updatedTime, Integer followCount) {
		this.accountId = accountId;
		this.name = name;
		this.coverPath = coverPath;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.followCount = followCount;
	}

	public Long getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Long albumId) {
		this.albumId = albumId;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCoverPath() {
		return this.coverPath;
	}

	public void setCoverPath(String coverPath) {
		this.coverPath = coverPath;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Integer getFollowCount() {
		return this.followCount;
	}

	public void setFollowCount(Integer followCount) {
		this.followCount = followCount;
	}

}
