package com.scoutin.entities;

// Generated Apr 9, 2013 12:16:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * Albumcard generated by hbm2java
 */
public class Albumcard implements java.io.Serializable {

	private AlbumcardId id;

	public Albumcard() {
	}

	public Albumcard(AlbumcardId id) {
		this.id = id;
	}

	public AlbumcardId getId() {
		return this.id;
	}

	public void setId(AlbumcardId id) {
		this.id = id;
	}

}
