package com.scoutin.entities;

// Generated Apr 11, 2013 7:58:42 AM by Hibernate Tools 4.0.0

/**
 * Albumcard generated by hbm2java
 */
public class Albumcard implements java.io.Serializable {

	private AlbumcardId id;
	private Card card;
	private Album album;

	public Albumcard() {
	}

	public Albumcard(AlbumcardId id, Card card, Album album) {
		this.id = id;
		this.card = card;
		this.album = album;
	}

	public AlbumcardId getId() {
		return this.id;
	}

	public void setId(AlbumcardId id) {
		this.id = id;
	}

	public Card getCard() {
		return this.card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

}
