package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

/**
 * Cardreposts generated by hbm2java
 */
public class Cardreposts implements java.io.Serializable {

	private CardrepostsId id;

	public Cardreposts() {
	}

	public Cardreposts(CardrepostsId id) {
		this.id = id;
	}

	public CardrepostsId getId() {
		return this.id;
	}

	public void setId(CardrepostsId id) {
		this.id = id;
	}

}
