package com.scoutin.entities;

// Generated Apr 9, 2013 12:16:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * Cardcategory generated by hbm2java
 */
public class Cardcategory implements java.io.Serializable {

	private CardcategoryId id;

	public Cardcategory() {
	}

	public Cardcategory(CardcategoryId id) {
		this.id = id;
	}

	public CardcategoryId getId() {
		return this.id;
	}

	public void setId(CardcategoryId id) {
		this.id = id;
	}

}
