package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

/**
 * Cardlikes generated by hbm2java
 */
public class Cardlikes implements java.io.Serializable {

	private CardlikesId id;

	public Cardlikes() {
	}

	public Cardlikes(CardlikesId id) {
		this.id = id;
	}

	public CardlikesId getId() {
		return this.id;
	}

	public void setId(CardlikesId id) {
		this.id = id;
	}

}
