package com.scoutin.entities;

// Generated Apr 11, 2013 7:58:42 AM by Hibernate Tools 4.0.0

/**
 * Cardlikes generated by hbm2java
 */
public class Cardlikes implements java.io.Serializable {

	private CardlikesId id;
	private Card card;
	private Account account;

	public Cardlikes() {
	}

	public Cardlikes(CardlikesId id, Card card, Account account) {
		this.id = id;
		this.card = card;
		this.account = account;
	}

	public CardlikesId getId() {
		return this.id;
	}

	public void setId(CardlikesId id) {
		this.id = id;
	}

	public Card getCard() {
		return this.card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

}
