package com.scoutin.entities;

// Generated Apr 9, 2013 12:16:10 AM by Hibernate Tools 3.4.0.CR1

/**
 * Cardlikes generated by hbm2java
 */
public class Cardlikes implements java.io.Serializable {

	private CardlikesId id;

	public Cardlikes() {
	}

	public Cardlikes(CardlikesId id) {
		this.id = id;
	}

	public CardlikesId getId() {
		return this.id;
	}

	public void setId(CardlikesId id) {
		this.id = id;
	}

}
