package com.scoutin.entities;

// Generated Apr 10, 2013 1:11:48 AM by Hibernate Tools 4.0.0

/**
 * Cardreposts generated by hbm2java
 */
public class Cardreposts implements java.io.Serializable {

	private CardrepostsId id;
	private Card card;
	private Account account;
	private Integer count;

	public Cardreposts() {
	}

	public Cardreposts(CardrepostsId id, Card card, Account account) {
		this.id = id;
		this.card = card;
		this.account = account;
	}

	public Cardreposts(CardrepostsId id, Card card, Account account,
			Integer count) {
		this.id = id;
		this.card = card;
		this.account = account;
		this.count = count;
	}

	public CardrepostsId getId() {
		return this.id;
	}

	public void setId(CardrepostsId id) {
		this.id = id;
	}

	public Card getCard() {
		return this.card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

}
