package com.scoutin.entities;

// Generated Apr 11, 2013 7:58:42 AM by Hibernate Tools 4.0.0

/**
 * Cardcategory generated by hbm2java
 */
public class Cardcategory implements java.io.Serializable {

	private CardcategoryId id;
	private Card card;
	private Category category;

	public Cardcategory() {
	}

	public Cardcategory(CardcategoryId id, Card card, Category category) {
		this.id = id;
		this.card = card;
		this.category = category;
	}

	public CardcategoryId getId() {
		return this.id;
	}

	public void setId(CardcategoryId id) {
		this.id = id;
	}

	public Card getCard() {
		return this.card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

}
