package com.scoutin.entities;

// Generated Apr 10, 2013 1:11:48 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cardstat generated by hbm2java
 */
public class Cardstat implements java.io.Serializable {

	private long cardstatId;
	private Card card;
	private Integer rating;
	private Integer commentsCount;
	private Integer repostsCount;
	private Integer likesCount;
	private Date createdTime;
	private Date updatedTime;
	private Set cardbodies = new HashSet(0);

	public Cardstat() {
	}

	public Cardstat(long cardstatId, Card card) {
		this.cardstatId = cardstatId;
		this.card = card;
	}

	public Cardstat(long cardstatId, Card card, Integer rating,
			Integer commentsCount, Integer repostsCount, Integer likesCount,
			Date createdTime, Date updatedTime, Set cardbodies) {
		this.cardstatId = cardstatId;
		this.card = card;
		this.rating = rating;
		this.commentsCount = commentsCount;
		this.repostsCount = repostsCount;
		this.likesCount = likesCount;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.cardbodies = cardbodies;
	}

	public long getCardstatId() {
		return this.cardstatId;
	}

	public void setCardstatId(long cardstatId) {
		this.cardstatId = cardstatId;
	}

	public Card getCard() {
		return this.card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	public Integer getRating() {
		return this.rating;
	}

	public void setRating(Integer rating) {
		this.rating = rating;
	}

	public Integer getCommentsCount() {
		return this.commentsCount;
	}

	public void setCommentsCount(Integer commentsCount) {
		this.commentsCount = commentsCount;
	}

	public Integer getRepostsCount() {
		return this.repostsCount;
	}

	public void setRepostsCount(Integer repostsCount) {
		this.repostsCount = repostsCount;
	}

	public Integer getLikesCount() {
		return this.likesCount;
	}

	public void setLikesCount(Integer likesCount) {
		this.likesCount = likesCount;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Set getCardbodies() {
		return this.cardbodies;
	}

	public void setCardbodies(Set cardbodies) {
		this.cardbodies = cardbodies;
	}

}
