package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

/**
 * Cardcategory generated by hbm2java
 */
public class Cardcategory implements java.io.Serializable {

	private CardcategoryId id;

	public Cardcategory() {
	}

	public Cardcategory(CardcategoryId id) {
		this.id = id;
	}

	public CardcategoryId getId() {
		return this.id;
	}

	public void setId(CardcategoryId id) {
		this.id = id;
	}

}
