package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.Date;

/**
 * Card generated by hbm2java
 */
public class Card implements java.io.Serializable {

	private Long cardId;
	private Long referenceId;
	private String title;
	private String description;
	private Byte rating;
	private Integer commentsCount;
	private Integer repostsCount;
	private Integer likesCount;
	private Date createdTime;
	private Date updatedTime;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private String address;
	private String tag;

	public Card() {
	}

	public Card(Long referenceId, String title, String description,
			Byte rating, Integer commentsCount, Integer repostsCount,
			Integer likesCount, Date createdTime, Date updatedTime,
			BigDecimal latitude, BigDecimal longitude, String address,
			String tag) {
		this.referenceId = referenceId;
		this.title = title;
		this.description = description;
		this.rating = rating;
		this.commentsCount = commentsCount;
		this.repostsCount = repostsCount;
		this.likesCount = likesCount;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
		this.latitude = latitude;
		this.longitude = longitude;
		this.address = address;
		this.tag = tag;
	}

	public Long getCardId() {
		return this.cardId;
	}

	public void setCardId(Long cardId) {
		this.cardId = cardId;
	}

	public Long getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(Long referenceId) {
		this.referenceId = referenceId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Byte getRating() {
		return this.rating;
	}

	public void setRating(Byte rating) {
		this.rating = rating;
	}

	public Integer getCommentsCount() {
		return this.commentsCount;
	}

	public void setCommentsCount(Integer commentsCount) {
		this.commentsCount = commentsCount;
	}

	public Integer getRepostsCount() {
		return this.repostsCount;
	}

	public void setRepostsCount(Integer repostsCount) {
		this.repostsCount = repostsCount;
	}

	public Integer getLikesCount() {
		return this.likesCount;
	}

	public void setLikesCount(Integer likesCount) {
		this.likesCount = likesCount;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

}
