package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Short categoryId;
	private String name;

	public Category() {
	}

	public Category(String name) {
		this.name = name;
	}

	public Short getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Short categoryId) {
		this.categoryId = categoryId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
