package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Long commentId;
	private long cardId;
	private int accountId;
	private String content;
	private Date updatedTime;
	private Date createdTime;

	public Comment() {
	}

	public Comment(long cardId, int accountId) {
		this.cardId = cardId;
		this.accountId = accountId;
	}

	public Comment(long cardId, int accountId, String content,
			Date updatedTime, Date createdTime) {
		this.cardId = cardId;
		this.accountId = accountId;
		this.content = content;
		this.updatedTime = updatedTime;
		this.createdTime = createdTime;
	}

	public Long getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Long commentId) {
		this.commentId = commentId;
	}

	public long getCardId() {
		return this.cardId;
	}

	public void setCardId(long cardId) {
		this.cardId = cardId;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
