package com.scoutin.entities;

// Generated Apr 10, 2013 1:11:48 AM by Hibernate Tools 4.0.0

/**
 * FollowerId generated by hbm2java
 */
public class FollowerId implements java.io.Serializable {

	private int followedId;
	private int followingId;

	public FollowerId() {
	}

	public FollowerId(int followedId, int followingId) {
		this.followedId = followedId;
		this.followingId = followingId;
	}

	public int getFollowedId() {
		return this.followedId;
	}

	public void setFollowedId(int followedId) {
		this.followedId = followedId;
	}

	public int getFollowingId() {
		return this.followingId;
	}

	public void setFollowingId(int followingId) {
		this.followingId = followingId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FollowerId))
			return false;
		FollowerId castOther = (FollowerId) other;

		return (this.getFollowedId() == castOther.getFollowedId())
				&& (this.getFollowingId() == castOther.getFollowingId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFollowedId();
		result = 37 * result + this.getFollowingId();
		return result;
	}

}
