package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

/**
 * Followalbum generated by hbm2java
 */
public class Followalbum implements java.io.Serializable {

	private FollowalbumId id;

	public Followalbum() {
	}

	public Followalbum(FollowalbumId id) {
		this.id = id;
	}

	public FollowalbumId getId() {
		return this.id;
	}

	public void setId(FollowalbumId id) {
		this.id = id;
	}

}
