package com.scoutin.entities;

// Generated Apr 9, 2013 11:45:35 PM by Hibernate Tools 4.0.0

/**
 * Followalbum generated by hbm2java
 */
public class Followalbum implements java.io.Serializable {

	private FollowalbumId id;

	public Followalbum() {
	}

	public Followalbum(FollowalbumId id) {
		this.id = id;
	}

	public FollowalbumId getId() {
		return this.id;
	}

	public void setId(FollowalbumId id) {
		this.id = id;
	}

}
