package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

/**
 * Follower generated by hbm2java
 */
public class Follower implements java.io.Serializable {

	private FollowerId id;
	private boolean isFollowPerson;

	public Follower() {
	}

	public Follower(FollowerId id, boolean isFollowPerson) {
		this.id = id;
		this.isFollowPerson = isFollowPerson;
	}

	public FollowerId getId() {
		return this.id;
	}

	public void setId(FollowerId id) {
		this.id = id;
	}

	public boolean isIsFollowPerson() {
		return this.isFollowPerson;
	}

	public void setIsFollowPerson(boolean isFollowPerson) {
		this.isFollowPerson = isFollowPerson;
	}

}
