package com.scoutin.entities;

// Generated Apr 11, 2013 7:58:42 AM by Hibernate Tools 4.0.0

/**
 * Followalbum generated by hbm2java
 */
public class Followalbum implements java.io.Serializable {

	private FollowalbumId id;
	private Album album;
	private Follower follower;

	public Followalbum() {
	}

	public Followalbum(FollowalbumId id, Album album, Follower follower) {
		this.id = id;
		this.album = album;
		this.follower = follower;
	}

	public FollowalbumId getId() {
		return this.id;
	}

	public void setId(FollowalbumId id) {
		this.id = id;
	}

	public Album getAlbum() {
		return this.album;
	}

	public void setAlbum(Album album) {
		this.album = album;
	}

	public Follower getFollower() {
		return this.follower;
	}

	public void setFollower(Follower follower) {
		this.follower = follower;
	}

}
