package com.scoutin.entities;

// Generated Apr 12, 2013 6:29:04 AM by Hibernate Tools 4.0.0

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private Long messageId;

	public Message() {
	}

	public Long getMessageId() {
		return this.messageId;
	}

	public void setMessageId(Long messageId) {
		this.messageId = messageId;
	}

}
