package com.scoutin.entities;

// Generated Apr 16, 2013 2:22:33 AM by Hibernate Tools 4.0.0

/**
 * Notification generated by hbm2java
 */
public class Notification implements java.io.Serializable {

	private Long notificationId;

	public Notification() {
	}

	public Long getNotificationId() {
		return this.notificationId;
	}

	public void setNotificationId(Long notificationId) {
		this.notificationId = notificationId;
	}

}
