package com.scoutin.entities;

// Generated Apr 4, 2013 10:13:24 PM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Picture generated by hbm2java
 */
public class Picture implements java.io.Serializable {

	private Long pictureId;
	private Card card;
	private Date createdTime;

	public Picture() {
	}

	public Picture(Card card, Date createdTime) {
		this.card = card;
		this.createdTime = createdTime;
	}

	public Long getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Long pictureId) {
		this.pictureId = pictureId;
	}

	public Card getCard() {
		return this.card;
	}

	public void setCard(Card card) {
		this.card = card;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
