package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Picture generated by hbm2java
 */
public class Picture implements java.io.Serializable {

	private Long pictureId;
	private Long cardId;
	private Date createdTime;

	public Picture() {
	}

	public Picture(Long cardId, Date createdTime) {
		this.cardId = cardId;
		this.createdTime = createdTime;
	}

	public Long getPictureId() {
		return this.pictureId;
	}

	public void setPictureId(Long pictureId) {
		this.pictureId = pictureId;
	}

	public Long getCardId() {
		return this.cardId;
	}

	public void setCardId(Long cardId) {
		this.cardId = cardId;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

}
