package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private int accountId;
	private String firstname;
	private String lastname;
	private String middlename;
	private Byte sex;
	private Date birthday;
	private String mobile;
	private Date createdTime;
	private Date updatedTime;

	public Profile() {
	}

	public Profile(int accountId) {
		this.accountId = accountId;
	}

	public Profile(int accountId, String firstname, String lastname,
			String middlename, Byte sex, Date birthday, String mobile,
			Date createdTime, Date updatedTime) {
		this.accountId = accountId;
		this.firstname = firstname;
		this.lastname = lastname;
		this.middlename = middlename;
		this.sex = sex;
		this.birthday = birthday;
		this.mobile = mobile;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public Byte getSex() {
		return this.sex;
	}

	public void setSex(Byte sex) {
		this.sex = sex;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
