package com.scoutin.entities;

// Generated Apr 11, 2013 7:59:48 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Profile generated by hbm2java
 */
public class Profile implements java.io.Serializable {

	private int accountId;
	private Account account;
	private String middlename;
	private Date birthday;
	private String mobile;
	private Date createdTime;
	private Date updatedTime;

	public Profile() {
	}

	public Profile(Account account) {
		this.account = account;
	}

	public Profile(Account account, String middlename, Date birthday,
			String mobile, Date createdTime, Date updatedTime) {
		this.account = account;
		this.middlename = middlename;
		this.birthday = birthday;
		this.mobile = mobile;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
