package com.scoutin.entities;

// Generated Apr 9, 2013 11:45:35 PM by Hibernate Tools 4.0.0

/**
 * Relationship16 generated by hbm2java
 */
public class Relationship16 implements java.io.Serializable {

	private Relationship16Id id;
	private Integer count;

	public Relationship16() {
	}

	public Relationship16(Relationship16Id id) {
		this.id = id;
	}

	public Relationship16(Relationship16Id id, Integer count) {
		this.id = id;
		this.count = count;
	}

	public Relationship16Id getId() {
		return this.id;
	}

	public void setId(Relationship16Id id) {
		this.id = id;
	}

	public Integer getCount() {
		return this.count;
	}

	public void setCount(Integer count) {
		this.count = count;
	}

}
