package com.scoutin.entities;

// Generated Apr 9, 2013 11:45:35 PM by Hibernate Tools 4.0.0

/**
 * Relationship15 generated by hbm2java
 */
public class Relationship15 implements java.io.Serializable {

	private Relationship15Id id;

	public Relationship15() {
	}

	public Relationship15(Relationship15Id id) {
		this.id = id;
	}

	public Relationship15Id getId() {
		return this.id;
	}

	public void setId(Relationship15Id id) {
		this.id = id;
	}

}
