package com.scoutin.entities;

// Generated Apr 9, 2013 11:45:35 PM by Hibernate Tools 4.0.0

/**
 * Relationship13Id generated by hbm2java
 */
public class Relationship13Id implements java.io.Serializable {

	private long albumId;
	private long cardId;

	public Relationship13Id() {
	}

	public Relationship13Id(long albumId, long cardId) {
		this.albumId = albumId;
		this.cardId = cardId;
	}

	public long getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(long albumId) {
		this.albumId = albumId;
	}

	public long getCardId() {
		return this.cardId;
	}

	public void setCardId(long cardId) {
		this.cardId = cardId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof Relationship13Id))
			return false;
		Relationship13Id castOther = (Relationship13Id) other;

		return (this.getAlbumId() == castOther.getAlbumId())
				&& (this.getCardId() == castOther.getCardId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getAlbumId();
		result = 37 * result + (int) this.getCardId();
		return result;
	}

}
