package com.scoutin.entities;

// Generated Apr 9, 2013 11:45:35 PM by Hibernate Tools 4.0.0

/**
 * Relationship13 generated by hbm2java
 */
public class Relationship13 implements java.io.Serializable {

	private Relationship13Id id;

	public Relationship13() {
	}

	public Relationship13(Relationship13Id id) {
		this.id = id;
	}

	public Relationship13Id getId() {
		return this.id;
	}

	public void setId(Relationship13Id id) {
		this.id = id;
	}

}
