package com.scoutin.entities;

// Generated Apr 9, 2013 11:45:35 PM by Hibernate Tools 4.0.0

/**
 * Relationship9 generated by hbm2java
 */
public class Relationship9 implements java.io.Serializable {

	private Relationship9Id id;

	public Relationship9() {
	}

	public Relationship9(Relationship9Id id) {
		this.id = id;
	}

	public Relationship9Id getId() {
		return this.id;
	}

	public void setId(Relationship9Id id) {
		this.id = id;
	}

}
