package com.scoutin.entities;

// Generated Apr 6, 2013 8:06:34 AM by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * Stat generated by hbm2java
 */
public class Stat implements java.io.Serializable {

	private int accountId;
	private Integer followingCount;
	private Integer followersCount;
	private Date lastRecmdView;
	private Integer unviewRecmdCount;

	public Stat() {
	}

	public Stat(int accountId) {
		this.accountId = accountId;
	}

	public Stat(int accountId, Integer followingCount, Integer followersCount,
			Date lastRecmdView, Integer unviewRecmdCount) {
		this.accountId = accountId;
		this.followingCount = followingCount;
		this.followersCount = followersCount;
		this.lastRecmdView = lastRecmdView;
		this.unviewRecmdCount = unviewRecmdCount;
	}

	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	public Integer getFollowingCount() {
		return this.followingCount;
	}

	public void setFollowingCount(Integer followingCount) {
		this.followingCount = followingCount;
	}

	public Integer getFollowersCount() {
		return this.followersCount;
	}

	public void setFollowersCount(Integer followersCount) {
		this.followersCount = followersCount;
	}

	public Date getLastRecmdView() {
		return this.lastRecmdView;
	}

	public void setLastRecmdView(Date lastRecmdView) {
		this.lastRecmdView = lastRecmdView;
	}

	public Integer getUnviewRecmdCount() {
		return this.unviewRecmdCount;
	}

	public void setUnviewRecmdCount(Integer unviewRecmdCount) {
		this.unviewRecmdCount = unviewRecmdCount;
	}

}
