package com.scoutin.entities;

// Generated Apr 1, 2013 6:45:42 PM by Hibernate Tools 4.0.0

/**
 * Message generated by hbm2java
 */
public class Message implements java.io.Serializable {

	private long messageId;

	public Message() {
	}

	public Message(long messageId) {
		this.messageId = messageId;
	}

	public long getMessageId() {
		return this.messageId;
	}

	public void setMessageId(long messageId) {
		this.messageId = messageId;
	}

}
